services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    environment:
      - POSTGRES_DB=gateway
      - POSTGRES_USER=tguser
      - POSTGRES_PASSWORD=somepwd
      - PGDATA=/usr/local/pgsql/data
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kind

volumes:
  postgres-data:
